
#cfg server
server:
  port: 9191


#cfg datasource
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    password: aakash
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
         
      
        
        
           

#configure view rsolver file

  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
      
#configure properties class prefixes
formapp:
   messages:
        succMsg: Registration Successful
        failureMsg: registration not successful

      
